### ISSUE TITLE
Open Source Tech for FedRamp Dashboard?

### ISSUE THREAD

**Issue by andrewhoppin** [18F/ads-bpa#26]
Congrats to TrueTandem on winning the first task order, to build a FEDRAMP dashboard.  We've recently released a react.js based set of open source data dashboard building tools, and we'd love to have them leveraged (and contributed to!) for this project, if useful: 

https://github.com/NuCivic/react-dashboard 

And regardless, we'd love to learn what tools TrueTandem does use for this dashboard, and see what new FOSS capabilities result!  :)

**Comment by jposi** [comment]
We ended up with an Angular app - you can view [the full repo on github](https://github.com/18F/fedramp-dashboard/)

**Comment by jposi** [comment]
I'm going to close this issue but feel free to ask questions or open issues on FedRAMP repo.
